const characters = [
    {
      characterClass: "Barbarian",
      special: 10,
      maxHp: 40,
      currentHp: 40,
      attack: 30,
      defense: 15,
      speed: [3, 5],
      dodge: 5,
    },
    {
      characterClass: "Rogue",
      special: 1,
      maxHp: 30,
      currentHp: 30,
      attack: 25,
      defense: 15,
      speed: [6, 8],
      dodge: 20,
    },
    {
      characterClass: "Ranger",
      special: 20,
      maxHp: 40,
      currentHp: 40,
      attack: 20,
      defense: 10,
      speed: [4, 6],
      dodge: 15,
    },
    {
      characterClass: "Wizard",
      special: 5,
      maxHp: 20,
      currentHp: 20,
      attack: 20,
      defense: 20,
      speed: [5, 7],
      dodge: 10,
    },
    {
      characterClass: "Cleric",
      special: 20,
      maxHp: 30,
      currentHp: 30,
      attack: 10,
      defense: 15,
      speed: [4, 6],
      dodge: 15,
    },
    {
      characterClass: "Druid",
      special: 10,
      maxHp: 30,
      currentHp: 30,
      attack: 15,
      defense: 20,
      speed: [2, 4],
      dodge: 10,
    },
    {
      characterClass: "Paladin",
      special: 10,
      maxHp: 60,
      currentHp: 60,
      attack: 15,
      defense: 30,
      speed: [1, 3],
      dodge: 5,
    },
    {
      characterClass: "Fighter",
      special: 5,
      maxHp: 50,
      currentHp: 50,
      attack: 20,
      defense: 20,
      speed: [2, 4],
      dodge: 5,
    },
];

export function findBaseStats(data) {
    return characters.find((character) => character.characterClass === data);
};